### ISSUE TITLE
CUDA 10

### ISSUE THREAD

**Issue by akurz-wue** [imodpasteur/ZOLA-3D#6]
Has anyone ever tried using higher versions of CUDA than 8 and succeeded? End of the year we spent some money for the new RTX 2080 Ti and it seems that only CUDA 10 is supported (no lower versions). I fear that this might be a dead end... :(

**Comment by benoitbenoit** [comment]
Hello,
I found libraries pre-compiled for linux and cuda10. You can find them in release section: https://github.com/imodpasteur/ZOLA-3D/releases/download/0.2.2/JCuda.libraries.zip
Best,
Benoit L

**Comment by akurz-wue** [comment]
I always get the following error:

(Fiji Is Just) ImageJ 2.0.0-rc-69/1.52i; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 44MB of 24440MB (<1%)
 
java.lang.UnsatisfiedLinkError: Error while loading native library "JCudaRuntime-0.9.0-windows-x86_64"
Operating system name: Windows 10
Architecture         : amd64
Architecture bit size: 64
---(start of nested stack traces)---
Stack trace from the attempt to load the library as a file:
java.lang.UnsatisfiedLinkError: no JCudaRuntime-0.9.0-windows-x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at jcuda.LibUtils.loadLibrary(LibUtils.java:143)
	at jcuda.runtime.JCuda.initialize(JCuda.java:422)
	at jcuda.runtime.JCuda.<clinit>(JCuda.java:406)
	at org.pasteur.imagej.cuda.MyCudaStream.init(MyCudaStream.java:58)
	at org.pasteur.imagej.ZOLA.phaseoptim(ZOLA.java:1687)
	at org.pasteur.imagej.ZOLA.run(ZOLA.java:522)
	at ij.IJ.runUserPlugIn(IJ.java:228)
	at ij.IJ.runPlugIn(IJ.java:192)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
Stack trace from the attempt to load the library as a resource:
java.io.IOException: No resource found with name '/lib/JCudaRuntime-0.9.0-windows-x86_64.dll'
	at jcuda.LibUtils.writeResourceToFile(LibUtils.java:323)
	at jcuda.LibUtils.loadLibraryResource(LibUtils.java:255)
	at jcuda.LibUtils.loadLibrary(LibUtils.java:158)
	at jcuda.runtime.JCuda.initialize(JCuda.java:422)
	at jcuda.runtime.JCuda.<clinit>(JCuda.java:406)
	at org.pasteur.imagej.cuda.MyCudaStream.init(MyCudaStream.java:58)
	at org.pasteur.imagej.ZOLA.phaseoptim(ZOLA.java:1687)
	at org.pasteur.imagej.ZOLA.run(ZOLA.java:522)
	at ij.IJ.runUserPlugIn(IJ.java:228)
	at ij.IJ.runPlugIn(IJ.java:192)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
---(end of nested stack traces)---

	at jcuda.LibUtils.loadLibrary(LibUtils.java:193)
	at jcuda.runtime.JCuda.initialize(JCuda.java:422)
	at jcuda.runtime.JCuda.<clinit>(JCuda.java:406)
	at org.pasteur.imagej.cuda.MyCudaStream.init(MyCudaStream.java:58)
	at org.pasteur.imagej.ZOLA.phaseoptim(ZOLA.java:1687)
	at org.pasteur.imagej.ZOLA.run(ZOLA.java:522)
	at ij.IJ.runUserPlugIn(IJ.java:228)
	at ij.IJ.runPlugIn(IJ.java:192)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)

**Comment by benoitbenoit** [comment]
I seems in the jars folder of fiji, you have [jcuda-0.9.0.jar, jcublas-0.9.0.jar, ...] files. Please, remove them and replace them by [jcuda-10.0.0.jar, jcublas-10.0.0.jar, ...] if your cuda version is 10.

**Comment by akurz-wue** [comment]
you are right, I forgot to remove the 0.9 versions... but nevertheless I get an error:
java.lang.UnsatisfiedLinkError: Error while loading native library "JCudaRuntime-10.0.0-windows-x86_64"
Operating system name: Windows 10
Architecture         : amd64
Architecture bit size: 64
---(start of nested stack traces)---
Stack trace from the attempt to load the library as a file:
java.lang.UnsatisfiedLinkError: no JCudaRuntime-10.0.0-windows-x86_64 in java.library.path
.....

**Comment by akurz-wue** [comment]
ah I guess the lib files have to be converted to .dll?

**Comment by benoitbenoit** [comment]
Sorry, I realize I put both 0.9.0 and 10.0.0 version in the folder you downloaded. The previous problem was my fault. Also, I provided Linux libraries and you use windows.

Please, download again the libraries (https://github.com/imodpasteur/ZOLA-3D/releases/download/0.2.2/JCuda.libraries.zip) and copy "JCuda.libraries/JCuda_10/windows/lib" in your fiji folder.

It should be fine know
Best,
benoit L

**Comment by akurz-wue** [comment]
you are the man! :D it works! thanks a lot!!
best,
andreas

**Comment by benoitbenoit** [comment]
Thank you,
Enjoy ZOLA-3D
Best,
Benoit Lelandais
