### ISSUE TITLE
Error when using sCMOS corrections

### ISSUE THREAD

**Issue by dpshepherd** [imodpasteur/ZOLA-3D#7]
Thanks for all of the hard work on ZOLA! We have a question because we are running into an error when using sCMOS correction. 

We are running ZOLA-3D on Windows 7 Pro 64-bit, ImageJ 1.52n, and Java 8.

Using a stack of PSFs we are able to successfully run Calibration: PSF modeling, using the GPU/CUDA 10, if we choose the Camera setup: EMCCD option for the camera. However, when we choose Camera setup:sCMOS and provide ZOLA-3D with the file paths for three needed files (16-bit TIFFs for offset, variance, and gain) that we normally utilize for fitting with the Huang et al algorithm in MATLAB, we get the following error:

----------
(Fiji Is Just) ImageJ 2.0.0-rc-69/1.52n; Java 1.8.0_131 [64-bit]; Windows 7 6.1; 1272MB of 96000MB (1%)
 
java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
 ^
	at java.util.regex.Pattern.error(Pattern.java:1955)
	at java.util.regex.Pattern.compile(Pattern.java:1702)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at java.lang.String.split(String.java:2380)
	at java.lang.String.split(String.java:2422)
	at org.pasteur.imagej.ZOLA.calibration(ZOLA.java:1862)
	at org.pasteur.imagej.ZOLA.run(ZOLA.java:340)
	at ij.IJ.runUserPlugIn(IJ.java:229)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
-----

I have tried to change the file delimiter to '\', \\', '\\\\', and '/' with no success. Any suggestions?

Thanks!

**Comment by benoitbenoit** [comment]
Hello,
Could you try the new version please : ZOLA-0.2.4 ?
You can download it here https://github.com/imodpasteur/ZOLA-3D/releases/download/2.4/ZOLA_-0.2.4-SNAPSHOT.jar
or update it using Fiji update site.
Thanks,
Benoit

**Comment by dpshepherd** [comment]
Hi Benoit,

The Calibration: PSF modeling window now loads, but it is not working correctly for sCMOS. 

First,  the offset and variance file paths are switched somewhere.
![image](https://user-images.githubusercontent.com/26783318/55882399-b5b4ef80-5b61-11e9-8ee4-724cc6b09312.png)

Second, if I manually switch the offset and variance paths, the calibration initializes and then immediately exits without generating a PSF fit.
![image](https://user-images.githubusercontent.com/26783318/55882632-193f1d00-5b62-11e9-94ea-1a9546b9495a.png)

> ZOLA version: 0.2.4-SNAPSHOT
> ZOLA PSF modeling started
> initialization started
> initialization 1/6
> initialization 2/6
> initialization 3/6
> initialization 4/6
> initialization 5/6
> initialization 6/6
> calibration started
> iteration: 0/30
> calibration finished
> residual (0) : NaN
> global residual : NaN
> calibration file saved
> elapsed time 0.0 min 5.0 sec
> 

If I run calibration using the same bead image with the camera set as an EMCCD (using values averaged over the entire sCMOS chip), we obtain a reasonable result using Calibration: PSF Modeling.

I can provide the bead images and sCMOS characterization images via Dropbox if it would be helpful?

Thanks,
Doug

**Comment by benoitbenoit** [comment]
Indeed, having data in a dropbox folder could help me resolving this bug.
Could you share it with me please ? 
My email address is the following: benoit.lelandais@pasteur.fr
(I am quite busy currently but I will try to solve this bug during the next few weeks.)
Thank you
